/// <auto-generated/> // https://github.com/DotNetAnalyzers/StyleCopAnalyzers/issues/3404
/// ^ global using에서 SA1200 경고가 발생하지만, stylecop은 이를 대응할 예정이 없는 것 같아 위와 같이 처리합니다.

global using Microsoft.VisualStudio.TestTools.UnitTesting;