// <auto-generated />
#nullable enable
namespace Binder.ViewModels;

using Binder.Models;

public partial class VmHome // generated by T4
{
    // ---------- 속성 : SelectedBindFile ----------
    private BindFile? selectedBindFile;
    public BindFile? SelectedBindFile
    {
        get => this.selectedBindFile;
        set => this.SetProperty(ref this.selectedBindFile, value);
    }

    // ---------- 속성 : SelectedExtract ----------
    private Extract? selectedExtract;
    public Extract? SelectedExtract
    {
        get => this.selectedExtract;
        set => this.SetProperty(ref this.selectedExtract, value);
    }

    // ---------- 속성 : SelectedExtractEnum ----------
    private ExtractEnum? selectedExtractEnum;
    public ExtractEnum? SelectedExtractEnum
    {
        get => this.selectedExtractEnum;
        set => this.SetProperty(ref this.selectedExtractEnum, value);
    }

}
