// <auto-generated />
#nullable enable
namespace Binder.ViewModels;

using Binder.Models;
using CommunityToolkit.Mvvm.Input;

public partial class VmHome // generated by T4
{
    // ---------- 속성 : SelectedBindFile ----------
    private BindFile? selectedBindFile;
    public BindFile? SelectedBindFile
    {
        get => this.selectedBindFile;
        set => this.SetProperty(ref this.selectedBindFile, value);
    }

    // ---------- 속성 : SelectedExtract ----------
    private Extract? selectedExtract;
    public Extract? SelectedExtract
    {
        get => this.selectedExtract;
        set => this.SetProperty(ref this.selectedExtract, value);
    }

    // ---------- 속성 : SelectedExtractEnum ----------
    private ExtractEnum? selectedExtractEnum;
    public ExtractEnum? SelectedExtractEnum
    {
        get => this.selectedExtractEnum;
        set => this.SetProperty(ref this.selectedExtractEnum, value);
    }

    // ---------- 속성 : SelectedExtractString ----------
    private ExtractString? selectedExtractString;
    public ExtractString? SelectedExtractString
    {
        get => this.selectedExtractString;
        set => this.SetProperty(ref this.selectedExtractString, value);
    }

	// ---------- 명령 : Extract? ----------
	public IRelayCommand ExtractAddCommand { get; }
	public IRelayCommand ExtractEditCommand { get; }
	public IRelayCommand ExtractDeleteCommand { get; }

	// ---------- 명령 : ExtractEnum? ----------
	public IRelayCommand ExtractEnumAddCommand { get; }
	public IRelayCommand ExtractEnumEditCommand { get; }
	public IRelayCommand ExtractEnumDeleteCommand { get; }

	// ---------- 명령 : ExtractString? ----------
	public IRelayCommand ExtractStringAddCommand { get; }
	public IRelayCommand ExtractStringEditCommand { get; }
	public IRelayCommand ExtractStringDeleteCommand { get; }

}
